 # Numpy
- Numerical Python
- homogeneous collection of elements
- numerical and scientific computing
- vectorization operation
- support multidimensional data(matrix)



In [1]:
pip install numpy

   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.7 MB 557.0 kB/s eta 0:00:22
   -- ------------------------------------- 0.8/12.7 MB 704.3 kB/s eta 0:00:17
   -- ------------------------------------- 0.8/12.7 MB 704.3 kB/s eta 0:00:17
   --- ------------------------------------ 1.0/12.7 MB 659.0 kB/s eta 0:00:18
   --- ------------------------------------ 1.0/12.7 MB 659.0 kB/s eta 0:00:18
   ---- ----------------------------------- 1.3/12.7 MB 672.0 kB/s eta 0:00:17
   ---- ----------------------------------- 1.3/12.7 MB 672.0 kB/s eta 0:00:17
   ---- ----------------------------------- 1.3/12.7 MB 672.0 kB/s eta 0:00:17
   ---- ----------


[notice] A new release of pip is available: 24.2 -> 25.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as n


In [4]:
x=n.array([5,7,9,4,2])
print(x)
print(type(x))

[5 7 9 4 2]
<class 'numpy.ndarray'>


# Attributes(shape,size,ndim,dtype)
# Functions()


In [6]:
#shape
print(x.shape)

(5,)


In [10]:
y=n.array([[2,4],[6,9]])
print(y)
print(y.shape)

[[2 4]
 [6 9]]
(2, 2)


In [11]:
#size
print(y.size)

4


In [12]:
#ndim-no.of dimensions
print(y.ndim)

2


#dtype
print(y.dtype)

# Functions in numpy array
1. n.sum()
2. n.prod()
3. n.max()
4. n.min()
5. n.mean()
6. n.std()
7. n.median()
8. n.sort()
9. n.unique()


In [14]:
#sum
print(n.sum(y))

21


In [15]:
print(n.prod(y))

432


In [17]:
print(n.max(y))
print(n.min(y))

9
2


In [18]:
print(n.mean(y))
print(n.median(y))
print(n.std(y))

5.25
5.0
2.5860201081971503


In [19]:
print(n.sort(y))

[[2 4]
 [6 9]]


In [20]:
print(n.unique(y))

[2 4 6 9]


# Indexing and Slicing

In [21]:
x= n.array([5,7,9,2,4])


In [22]:
print(x[1:3])

[7 9]


In [23]:
y=x[:3].copy()
print(y)

[5 7 9]


# Array Arithmetic
- n.add()
- n.subtract()
- n.multiply()
- n.divide()
- n.floor_divide()
- n.mod()
- n.power()
- n.sqrt()

In [3]:
x=n.array([2,4,6,8,10])
y=n.array([1,3,5,7,9])
z=n.add(x,y)
print(z)
sum=x+y
print(sum)

[ 3  7 11 15 19]
[ 3  7 11 15 19]


In [7]:
sub=n.subtract(x,y)
print(sub)

[1 1 1 1 1]


In [9]:
mul=n.multiply(x,y)
print(mul)

[ 2 12 30 56 90]


In [11]:
div=n.divide(x,y)
print(div)

[2.         1.33333333 1.2        1.14285714 1.11111111]


In [13]:
floor=n.floor_divide(x,y)
print(floor)

[2 1 1 1 1]


In [14]:
mod=n.mod(x,y)
print(mod)

[0 1 1 1 1]


In [15]:
pow=n.power(x,y)
print(pow)

[         2         64       7776    2097152 1000000000]


In [18]:
squarex=n.sqrt(x)
print(squarex)
squarey=n.sqrt(y)
print(squarey)


[1.41421356 2.         2.44948974 2.82842712 3.16227766]
[1.         1.73205081 2.23606798 2.64575131 3.        ]


Reshaping of arrays,iterating over arrays,broadcasting,creating numpy array from numerical range

# Creating numpy array from numerical range
Use np.arange() or np.linspace(): and
ones,
,zeros
,full


In [3]:
import numpy as np

# Using arange (similar to Python's range)
arr1 = np.arange(0, 10, 2).reshape(5,1) #arange(start,stop,step)
print(arr1)

# Using linspace (specify number of values)
arr2 = np.linspace(0, 1, 10)  
print(arr2)


[[0]
 [2]
 [4]
 [6]
 [8]]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [13]:
#Creates an array filled with 1s
a= np.ones((2,3))
print(a)
#Creates an array filled with 0s
b=np.zeros((2,3))
print(b)
# Creates an array filled with a specified value
c=np.full((4,2),5)
print(c)

[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[5 5]
 [5 5]
 [5 5]
 [5 5]]


# Reshaping of arrays
  Use .reshape(rows, cols) to change dimensions

In [3]:
a = np.arange(1,7)       
b = a.reshape(2, 3).copy()
print(b)

[[1 2 3]
 [4 5 6]]


# Iterating over arrays


In [6]:
arr = np.array([[1, 2], [3, 4]])

# Row-wise
for row in arr:
    print(row)

# Element-wise using flat
for elem in arr.flat:
    print(elem)
#nestedloop to print element wise
for i in arr:
    for j in i:
        print(j)

[1 2]
[3 4]
1
2
3
4
1
2
3
4


In [5]:
arr.flatten()

array([1, 2, 3, 4])

# Broadcasting

In [11]:
#Adding a scalar to an array
a = np.array([1, 2, 3])
b = a + 10 
print(b)

[11 12 13]


In [12]:
#Adding arrays of different shapes
a = np.array([[1], [2], [3]])  # shape (3,1)
b = np.array([10, 20, 30])     # shape (3,)
c = a + b 
print(c)

[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [18]:
a=np.ones((3,3))+np.arange(3)
print(a)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [5]:
a=np.arange(3).reshape((3,1))+np.arange(3)
print(a)

[[0 1 2]
 [1 2 3]
 [2 3 4]]


# Sorting and searching
1. sorted()
2. np.sort()
3. np.argsort()

In [15]:
x= np.array([4,1,2,3])
y=sorted(x).copy()
print(y)


[np.int64(1), np.int64(2), np.int64(3), np.int64(4)]


In [18]:
print(np.sort(x))
#Reversing
z=np.sort(x)
print(z[::-1])

[1 2 3 4]
[4 3 2 1]


In [19]:
print(np.argsort(x))

[1 2 3 0]


# Searching
1. np.where()
2. .argmax()
3. .argmin()
4. in
   

In [22]:
x=np.array([1,2,3,4,5])
np.where(x>=2)

(array([1, 2, 3, 4]),)

In [25]:

print(np.argmax(x)) 
print(np.argmin(x))

4
0


# Using in with NumPy Arrays

In [5]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(3 in arr)   
print(10 in arr)  


True
False


In [4]:
arr = np.array([1, 2, 3, 4, 5])
values = [2, 5, 10]

result = np.isin(arr, values)
print(result)


[False  True False False  True]
